package product_catalog_system.domain;

// Generated 4/04/2015 10:16:30 AM by Hibernate Tools 3.4.0.CR1

/**
 * Attachments generated by hbm2java
 */
public class Attachments implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String attachment;

	public Attachments() {
	}

	public Attachments(Product product, String attachment) {
		this.product = product;
		this.attachment = attachment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

}
