package product_catalog_system.domain;

// Generated 4/04/2015 10:16:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Catalog generated by hbm2java
 */
public class Catalog implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private Set products = new HashSet(0);

	public Catalog() {
	}

	public Catalog(String id) {
		this.id = id;
	}

	public Catalog(String name, String description, Set products) {
		this.name = name;
		this.description = description;
		this.products = products;
	}
	
	public Catalog(String id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
